# Generated by Django 3.1.1 on 2020-09-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_eventspage',
            name='image',
            field=models.FileField(blank=True, upload_to='event_images'),
        ),
        migrations.AddField(
            model_name='admin_eventspage',
            name='tag_line',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
