# Generated by Django 3.1.1 on 2020-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=500)),
                ('speaker', models.CharField(max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('event_date', models.DateField(null=True, verbose_name='Date')),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Mid-Afternoon', 'Mid-Afternoon'), ('Afternoon', 'Afternoon')], max_length=100)),
                ('room_capacity', models.PositiveIntegerField()),
                ('events_image', models.ImageField(upload_to='event_images')),
            ],
        ),
    ]
