# Generated by Django 3.1.1 on 2020-10-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Mid-Morning', 'Mid-Morning'), ('Afternoon', 'Afternoon')], max_length=100),
        ),
    ]
