# Generated by Django 3.1.1 on 2020-10-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201001_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='room_capacity',
            field=models.PositiveIntegerField(blank=True, max_length=250, null=True),
        ),
    ]
