# Generated by Django 3.1.1 on 2020-10-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201002_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='room_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
